Messages:
  Reloaded: "&eImageFrame已重新加载！"
  ImageMapProcessing: "&c正在处理ImageMap，请稍候！"
  ImageMapCreated: "&aImageMap已创建！"
  ImageMapRefreshed: "&aImageMap已刷新！"
  ImageMapDeleted: "&eImageMap已删除！"
  ImageMapRenamed: "&aImageMap已重命名！"
  ImageMapTogglePaused: "&a切换ImageMap播放暂停！"
  ImageMapPlaybackJumpTo: "&a跳转到{Seconds}秒的位置！"
  ImageMapPlayerPurge: "&e清除{CreatorName} ({CreatorUUID})拥有的{Amount}个ImageMap - [{ImageMapNames}]"
  SetCreator: "&a将ID为{ImageID}的ImageMap创建者设置为{CreatorName} ({CreatorUUID})"
  InvalidOverlayMap: "&c叠加层仅适用于原版Minecraft地图，且选择中不得有重复项！"
  UnableToLoadMap: "&c无法加载ImageMap，读取图像时出现问题。请联系服务器管理员查看更多信息。"
  UnknownError: "&c发生未知错误。"
  ImageOverMaxFileSize: "&c无法加载ImageMap，因为其文件大小超过允许的最大值。({Size}字节)"
  NotAnImageMap: "&c这不是一个ImageMap"
  URLImageMapInfo:
    - "&bImageID: {ImageID}"
    - "&a名称: {Name}"
    - "&e地图大小: {Width} x {Height}"
    - "&d创建者: {CreatorName} ({CreatorUUID})"
    - "&f访问权限: {Access}"
    - "&a创建时间: {TimeCreated}"
    - "&b标记: {Markers}"
    - "&eURL: {URL}"
  NoPermission: "&c您没有执行此操作的权限！"
  NoConsole: "&c此命令仅可由玩家执行！"
  PlayerNotFound: "&c找不到该玩家！"
  InvalidUsage: "&c用法无效！"
  NotEnoughMaps: "&c您没有{Amount}个地图！"
  Oversize: "&c太大了！地图的最大尺寸为{MaxSize}"
  URLRestricted: "&c该URL受限制，无法用于创建图像地图。"
  PlayerCreationLimitReached: "&c您一次只能创建<Limit>个地图！请删除一些地图以创建新的地图"
  DuplicateMapName: "&c您已经使用该名称创建了一个图像地图！"
  MapLookup: "&b{CreatorName} ({CreatorUUID})创建的图像地图列表："
  ItemFrameOccupied: "&c无法在选定的物品展示框上放置或移除某些地图，它们可能已被销毁、替换、占用或受保护。"
  NotEnoughSpace: "&c由于空间不足，无法放置组合图像地图。"
  AccessPermission:
    Updated: "&a已更新{PlayerName} ({PlayerUUID})的访问权限，他们现在拥有{Permission}权限。"
    Types:
      NONE: "无"
      GET: "获取"
      MARKER: "标记"
      EDIT: "编辑"
      EDIT_CLONE: "克隆编辑"
      ALL: "全部"
  Selection:
    Begin: "&b右键单击物品展示框选择第1和第2个角落"
    Clear: "&e退出选择模式"
    Corner1: "&a已选择物品展示框第1个角落"
    Corner2: "&a已选择物品展示框第2个角落"
    Invalid: "&c选择无效！"
    Oversize: "&c选择过大！地图的最大尺寸为{MaxSize}"
    Success: "&a选择了{Width} x {Height}个物品展示框！&e如果其中任何一个被移除/替换，您将需要重新选择。"
    NoSelection: "&c您还没有有效的选择。"
    IncorrectSize: "&c您的选择尺寸不匹配，需要{Width} x {Height}。"
  Markers:
    AddBegin: '&a右键单击包含地图"{Name}"的物品展示框以放置标记！&b运行"/imageframe marker cancel"取消放置'
    AddConfirm: "&a标记已放置！"
    Remove: "&e标记已移除！"
    Clear: "&e清除标记！"
    Cancel: "&e取消标记放置！"
    DuplicateName: "&c已经有一个使用该名称的标记！"
    NotAMarker: "&c这不是一个有效的标记"
    NotRenderOnFrameWarning: "&e警告：此标记类型不在物品展示框上显示！"
    LimitReached: "&c您只能在一个地图上创建{Limit}个标记！"
  # 日期格式用于显示基于时间的变量
  DateFormat: "dd/MM/yyyy HH:mm:ss zzz"
  Preferences:
    Keys:
      VIEW_ANIMATED_MAPS: "查看动画地图"
    Values:
      "TRUE": "&a已启用"
      "FALSE": "&c已禁用"
      UNSET: "&7未设置"
    UpdateMessage: "&e玩家偏好{Preference}&e已更新为{Value}&e！"

Settings:
  MapItemFormat: "&f{Name} &7({X}, {Y})"
  #Whether empty maps are required to create image maps when not in creative
  RequireEmptyMaps: true
  #Max size of an image map
  MaxSize: 100
  #When enabled, Only websites from the list below is allowed to be shown through in-game maps
  RestrictImageUrl:
    Enabled: false
    Whitelist:
      - "https://i.imgur.com"
      - "http://i.imgur.com"
      - "https://storage.googleapis.com"
      - "http://storage.googleapis.com"
      - "https://cdn.discordapp.com"
      - "http://cdn.discordapp.com"
      - "https://media.discordapp.net"
      - "http://media.discordapp.net"
      - "https://textures.minecraft.net"
      - "http://textures.minecraft.net"
  # If the image is larger than the defined size, it won't be downloaded for preview
  # (In Bytes)
  MaxImageFileSize: 52428800
  #Max amount of image maps a player in the following groups can create
  #Setting -1 means unlimited
  #To add a player to a group, give the permission "imageframe.createlimit.<group>"
  #For example "imageframe.createlimit.vip"
  #Players with no groups will be treated as "default" unless they have "imageframe.createlimit.unlimited"
  PlayerCreationLimit:
    default: 20
    vip: 25
    moderator: 30
  #Max amount of markers on an individual map
  MapMarkerLimit: 20
  CombinedMapItem:
    Name: "&b图像地图 &f- &f{Name} &7({Width} x {Height})"
    Lore:
    - "&a右键单击尺寸为{Width} x {Height}的物品展示框放置图像地图"
    - ""
    - "&7ImageID: {ImageID}"
    - "&7创建者: {CreatorName} ({CreatorUUID})"
    - "&7创建时间: {TimeCreated}"
  #How many map packets can be sent to a player in 1/20 of a second
  #You can turn this down if you are facing network issues
  #However maps might take longer to show to a player
  #To disable the rate limit, set to -1
  MapPacketSendingRateLimit: -1
  #Exempt certain map ids from deletion if their ImageFrame map is deleted
  #Values can be map ids (For example: "13") or ranges (inclusive) of map ids (For example: "10-13")
  ExemptMapIdsFromDeletion:
    - "-1"
  #This option should only be useful to developers and people who knew what they are doing
  MapRenderersContextual: false
  #Changing this option requires a restart
  HandleAnimatedMapsOnMainThread: false
  SendAnimatedMapsOnMainThread: false

Hooks:
  ViaVersion:
    #Enable this if your players below 1.13 is having network issues
    DisableSmoothAnimationForLegacyPlayers: false

#Enable update notifications for admins
Updater: true